"""Added Realtionships 

Revision ID: 1e18465ae189
Revises: 74245eb5f570
Create Date: 2026-07-22 20:17:56.924843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e18465ae189'
down_revision: Union[str, Sequence[str], None] = '74245eb5f570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_logs', sa.Column('trip_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'fuel_logs', 'trips', ['trip_id'], ['trip_id'])
    op.add_column('maintenance_logs', sa.Column('trip_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'maintenance_logs', 'trips', ['trip_id'], ['trip_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance_logs', type_='foreignkey')
    op.drop_column('maintenance_logs', 'trip_id')
    op.drop_constraint(None, 'fuel_logs', type_='foreignkey')
    op.drop_column('fuel_logs', 'trip_id')
    # ### end Alembic commands ###
