"""Added column to Trip

Revision ID: 74245eb5f570
Revises: 00cb64182be7
Create Date: 2026-07-22 14:19:59.606071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74245eb5f570'
down_revision: Union[str, Sequence[str], None] = '00cb64182be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('estimated_cost', sa.Float(), server_default='0.0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'estimated_cost')
    # ### end Alembic commands ###
