"""added COlumn 

Revision ID: d937e4d795a5
Revises: 1e18465ae189
Create Date: 2026-07-22 21:32:32.295591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd937e4d795a5'
down_revision: Union[str, Sequence[str], None] = '1e18465ae189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_logs', sa.Column('maintenance_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fuel_logs', 'maintenance_logs', ['maintenance_id'], ['maintenance_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fuel_logs', type_='foreignkey')
    op.drop_column('fuel_logs', 'maintenance_id')
    # ### end Alembic commands ###
